# Generated by Django 3.2.6 on 2021-12-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_duration_in_seconds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='comment_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='dislike_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration_in_seconds',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='like_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
