# Generated by Django 3.2.3 on 2021-07-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210613_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_deleted_private_videos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='open_search_new_tab',
            field=models.BooleanField(default=True),
        ),
    ]
