# Generated by Django 3.2.3 on 2021-07-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210702_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imported_yt_playlists',
            field=models.BooleanField(default=False),
        ),
    ]
