# Generated by Django 3.2.3 on 2021-07-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_imported_yt_playlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='import_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
