# Generated by Django 3.2.3 on 2021-07-05 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_import_in_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='just_joined',
            new_name='show_import_page',
        ),
    ]
