# Generated by Django 3.2.3 on 2021-07-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_just_joined_profile_show_import_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hide_deleted_private_videos',
            new_name='hide_unavailable_videos',
        ),
        migrations.AddField(
            model_name='profile',
            name='confirm_before_deleting',
            field=models.BooleanField(default=True),
        ),
    ]
