# Generated by Django 3.2.3 on 2021-07-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210712_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Untube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_likes', models.IntegerField(default=0)),
            ],
        ),
    ]
