# Generated by Django 3.2.3 on 2021-07-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_enable_gradient_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auto_check_for_updates',
            field=models.BooleanField(default=False),
        ),
    ]
