# Generated by Django 3.2.3 on 2021-07-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_auto_check_for_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hide_unavailable_videos',
            field=models.BooleanField(default=True),
        ),
    ]
