# Generated by Django 3.2.6 on 2021-08-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_profile_auto_check_for_updates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='untube_user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='manage_playlists_import_textarea',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yt_channel_id',
            field=models.TextField(default=''),
        ),
    ]
