# Generated by Django 3.2.3 on 2021-06-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=150)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('thumbnail_url', models.CharField(blank=True, max_length=420)),
                ('description', models.CharField(default='No description', max_length=420)),
                ('video_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('playlist_yt_player_HTML', models.CharField(blank=True, max_length=420)),
                ('playlist_duration', models.CharField(blank=True, max_length=69)),
                ('playlist_duration_in_seconds', models.IntegerField(default=0)),
                ('has_unavailable_videos', models.BooleanField(default=False)),
                ('channel_id', models.CharField(blank=True, max_length=420)),
                ('channel_name', models.CharField(blank=True, max_length=420)),
                ('user_notes', models.CharField(default='', max_length=420)),
                ('marked_as', models.CharField(default='', max_length=100)),
                ('is_favorite', models.BooleanField(blank=True, default=False)),
                ('num_of_accesses', models.IntegerField(default='0')),
                ('has_playlist_changed', models.BooleanField(default=False)),
                ('is_private_on_yt', models.BooleanField(default=False)),
                ('is_from_yt', models.BooleanField(default=True)),
                ('has_duplicate_videos', models.BooleanField(default=False)),
                ('view_in_grid_mode', models.BooleanField(default=False)),
                ('is_in_db', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('duration_in_seconds', models.IntegerField(default=0)),
                ('thumbnail_url', models.CharField(blank=True, max_length=420)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(default='', max_length=420)),
                ('has_cc', models.BooleanField(blank=True, default=False, null=True)),
                ('user_notes', models.CharField(default='', max_length=420)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('yt_player_HTML', models.CharField(blank=True, max_length=420)),
                ('channel_id', models.CharField(blank=True, max_length=420)),
                ('channel_name', models.CharField(blank=True, max_length=420)),
                ('video_position', models.CharField(blank=True, max_length=69)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_unavailable_on_yt', models.BooleanField(default=False)),
                ('was_deleted_on_yt', models.BooleanField(default=False)),
                ('is_marked_as_watched', models.BooleanField(blank=True, default=False)),
                ('is_favorite', models.BooleanField(blank=True, default=False)),
                ('num_of_accesses', models.CharField(default='0', max_length=69)),
                ('user_label', models.CharField(default='', max_length=100)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.playlist')),
            ],
        ),
    ]
