# Generated by Django 3.2.3 on 2021-06-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_position',
            field=models.IntegerField(blank=True),
        ),
    ]
