# Generated by Django 3.2.3 on 2021-06-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='is_in_db',
        ),
    ]
