# Generated by Django 3.2.3 on 2021-06-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_video_video_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='channel_id',
            field=models.CharField(default='', max_length=420),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_name',
            field=models.CharField(default='', max_length=420),
        ),
    ]
