# Generated by Django 3.2.3 on 2021-06-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_playlist_is_in_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_in_db',
            field=models.BooleanField(default=False),
        ),
    ]
