# Generated by Django 3.2.3 on 2021-06-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_playlist_is_in_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user_label',
            field=models.CharField(default='', max_length=100),
        ),
    ]
