# Generated by Django 3.2.3 on 2021-06-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210616_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_updates_text',
            field=models.CharField(default='', max_length=420),
        ),
    ]
