# Generated by Django 3.2.3 on 2021-06-24 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_playlist_playlist_updates_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_updates_text',
        ),
    ]
