# Generated by Django 3.2.3 on 2021-07-06 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210705_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='playlist_items',
        ),
        migrations.DeleteModel(
            name='PlaylistItem',
        ),
    ]
