# Generated by Django 3.2.3 on 2021-07-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210705_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_changed_text',
        ),
    ]
