# Generated by Django 3.2.3 on 2021-07-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='tags',
            field=models.ManyToManyField(related_name='playlists', to='main.Tag'),
        ),
    ]
