# Generated by Django 3.2.3 on 2021-07-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_playlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='num_videos_marked_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='is_marked_watched',
            field=models.BooleanField(default=False),
        ),
    ]
