# Generated by Django 3.2.3 on 2021-07-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210709_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='num_videos_marked_watched',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_marked_watched',
        ),
        migrations.AddField(
            model_name='playlist',
            name='watch_time_left',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='video',
            name='is_marked_as_watched',
            field=models.BooleanField(default=False),
        ),
    ]
