# Generated by Django 3.2.3 on 2021-07-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210709_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='last_watched',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='started_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
