# Generated by Django 3.2.3 on 2021-07-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210709_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='num_videos_watched',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='marked_as',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
