# Generated by Django 3.2.3 on 2021-07-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210709_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='percent_complete',
            field=models.FloatField(default=0),
        ),
    ]
