# Generated by Django 3.2.3 on 2021-07-11 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_playlist_percent_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='num_videos_watched',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='percent_complete',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='watch_time_left',
        ),
    ]
