# Generated by Django 3.2.3 on 2021-07-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210711_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='times_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
