# Generated by Django 3.2.3 on 2021-07-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='view_in_grid_mode',
            new_name='confirm_before_deleting',
        ),
        migrations.AddField(
            model_name='playlist',
            name='hide_unavailable_videos',
            field=models.BooleanField(default=False),
        ),
    ]
