# Generated by Django 3.2.3 on 2021-07-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210712_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='confirm_before_deleting',
            field=models.BooleanField(default=True),
        ),
    ]
