# Generated by Django 3.2.3 on 2021-07-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_playlist_confirm_before_deleting'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='last_accessed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
