# Generated by Django 3.2.3 on 2021-07-12 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_playlist_last_accessed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='last_accessed_on',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
