# Generated by Django 3.2.3 on 2021-07-12 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_playlist_last_accessed_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='last_accessed_on',
        ),
    ]
