# Generated by Django 3.2.3 on 2021-07-15 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_untube'),
        ('main', '0025_playlist_last_accessed_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(default='', max_length=420)),
                ('name', models.CharField(default='', max_length=420)),
                ('description', models.CharField(default='No description', max_length=420)),
                ('thumbnail_url', models.CharField(blank=True, max_length=420)),
                ('published_at', models.DateTimeField(blank=True)),
                ('view_count', models.IntegerField(default=0)),
                ('subscriberCount', models.IntegerField(default=0)),
                ('hidden_subscriber_count', models.BooleanField(null=True)),
                ('video_ount', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='user_label',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='user_notes',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='video_details_modified',
        ),
        migrations.RemoveField(
            model_name='playlistitem',
            name='video_details_modified_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_duplicate',
        ),
        migrations.RemoveField(
            model_name='video',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='video',
            name='playlist_item_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_position',
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='channel_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='channel_title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='video_item_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='untube_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_id',
            field=models.CharField(blank=True, max_length=420),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_name',
            field=models.CharField(blank=True, max_length=420),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='main.video'),
        ),
    ]
