# Generated by Django 3.2.3 on 2021-07-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210715_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistitem',
            old_name='video_item_id',
            new_name='playlist_video_id',
        ),
    ]
