# Generated by Django 3.2.3 on 2021-07-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_video_item_id_playlistitem_playlist_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='public_stats_viewable',
            field=models.BooleanField(default=True),
        ),
    ]
