# Generated by Django 3.2.3 on 2021-07-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210715_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(related_name='playlists', to='main.Video'),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.video'),
        ),
    ]
