# Generated by Django 3.2.3 on 2021-07-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_untube'),
        ('main', '0029_auto_20210715_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tags', to='users.profile'),
        ),
    ]
