# Generated by Django 3.2.3 on 2021-07-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210715_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistitem',
            old_name='channel_title',
            new_name='channel_name',
        ),
    ]
