# Generated by Django 3.2.3 on 2021-07-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_rename_channel_title_playlistitem_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlistitem',
            name='vid_id',
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlistitem',
            name='num_of_accesses',
            field=models.IntegerField(default=0),
        ),
    ]
