# Generated by Django 3.2.3 on 2021-07-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210715_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistitem',
            old_name='added_on',
            new_name='published_at',
        ),
    ]
