# Generated by Django 3.2.3 on 2021-07-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_playlist_is_yt_mix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='num_of_accesses',
            field=models.IntegerField(default=0),
        ),
    ]
