# Generated by Django 3.2.3 on 2021-07-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210720_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='has_duplicate_videos',
        ),
    ]
