# Generated by Django 3.2.3 on 2021-07-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_remove_playlist_has_duplicate_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
