# Generated by Django 3.2.3 on 2021-07-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_video_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='type',
            new_name='kind',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='has_unavailable_videos',
        ),
    ]
