# Generated by Django 3.2.3 on 2021-07-24 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20210722_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='video',
            name='is_pinned',
        ),
    ]
