# Generated by Django 3.2.3 on 2021-07-31 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210723_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='last_views_reset',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
