# Generated by Django 3.2.3 on 2021-07-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_tag_last_views_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='times_viewed_per_week',
            field=models.IntegerField(default=0),
        ),
    ]
