# Generated by Django 3.2.3 on 2021-07-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_tag_times_viewed_per_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='confirm_before_deleting',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='hide_unavailable_videos',
        ),
        migrations.AlterField(
            model_name='video',
            name='user_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='user_notes',
            field=models.CharField(blank=True, max_length=420),
        ),
    ]
