# Generated by Django 3.2.3 on 2021-08-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_playlist_auto_check_for_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_planned_to_watch',
            field=models.BooleanField(default=False),
        ),
    ]
