# Generated by Django 3.2.6 on 2021-08-04 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_video_is_planned_to_watch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='playlist_yt_player_HTML',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='thumbnail_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user_notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='user_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='yt_player_HTML',
            field=models.TextField(blank=True),
        ),
    ]
